repos:
  - repo: local
    hooks:
      - id: test
        name: test
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - files: ^cyantic/
        id: ruff
        name: ruff
        entry: uv run ruff format cyantic
        language: system
        stages: [pre-commit]
        types: [file, python]
      - files: ^cyantic/
        id: pyright
        name: pyright
        entry: uv run pyright cyantic
        language: system
        stages: [pre-commit]
        types: [file, python]
