repos:
  - repo: local
    hooks:
      - id: test
        name: test
        entry: rye run pytest
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - files: ^cast/
        id: ruff
        name: ruff
        entry: rye run ruff format
        language: system
        stages: [pre-commit]
        types: [file, python]
      - files: ^cast/
        id: pyright
        name: pyright
        entry: rye run pyright
        language: system
        stages: [pre-commit]
        types: [file, python]
